analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3490211,"name"\:"OrangeHRM Trial \#3490211","teamId"\:3482378,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3504735,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3482378,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
