<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_admin-login-password-input</name>
   <tag></tag>
   <elementGuidId>364d789c-9781-44ea-87c6-f76f83c13ce4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='admin-login-password-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#admin-login-password-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;············&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>237b0e02-310d-4a93-a37b-01d39984eb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>············</value>
      <webElementGuid>e9e0c09e-d5be-416f-8727-8d00633bc5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c2199ed1-e466-41a4-9fb3-ac4e4066f018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1bbcb76c-2351-480c-a0fd-b699b8d10ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-login-password-input</value>
      <webElementGuid>3b13a4c5-778c-4713-add5-5eb984efe768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-login-password-input-messages</value>
      <webElementGuid>55bdc6be-c00e-4523-8db5-63f42f70658b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>2e91a967-4a4c-4783-b09a-4ca355f2806c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin-login-password-input&quot;)</value>
      <webElementGuid>2a1109d1-6535-4307-93e7-876a8811eada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='admin-login-password-input']</value>
      <webElementGuid>91e935ef-f201-4e80-acfb-d4ee0f56b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='admin-login-form']/div/div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>40ab8b35-2dc8-40c6-975e-f016ce8ed1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[3]/input</value>
      <webElementGuid>9084c4a3-f7df-4a5a-8b6c-10658d6a5e77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '············' and @type = 'password' and @id = 'admin-login-password-input']</value>
      <webElementGuid>d1d3d380-7dc8-4cbd-9eae-6e83d9349649</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
