<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>4d759a64-107d-4ccc-853a-35b1ee1c0ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-login-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-login-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;············&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1135c481-8f8e-47aa-aaba-11921c522d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>············</value>
      <webElementGuid>f6090253-2867-4b30-8816-d3e60973790e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fd30734a-9dce-4a64-86b8-bd8a477387f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d5fcd6d5-b69d-4377-9da1-209bb50c2be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-login-password-input</value>
      <webElementGuid>12c3af80-90c6-4ca9-9bee-b896183e3eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-login-password-input-messages</value>
      <webElementGuid>ea5629e8-1da8-47eb-a588-a78b7ce7df81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>fb1b2793-9970-4a70-9eca-aec2d5662eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32cadad1fbc6d1831165e0c758e153a1</value>
      <webElementGuid>7add45bf-e223-47dc-a100-5d2703f9a2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-password-input']</value>
      <webElementGuid>94d1b4c5-9228-4f96-9a2b-9e2525f9615f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-password-input']</value>
      <webElementGuid>cf96fb3d-6656-43bf-9b53-7ac8be8c3efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '············' and @type = 'password' and @id = 'admin-login-password-input']</value>
      <webElementGuid>23f72f38-8430-4632-af76-70263daf02d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
