<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_v-field_input</name>
   <tag></tag>
   <elementGuidId>b23b4ad8-1e68-4cc6-ae85-71a74c2a8881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.v-field__input[data-no-activator=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-field__input ') and (@data-no-activator = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.app-select > .v-input > .v-input__control > .v-field > .v-field__field > .v-field__input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>598ddd35-222e-4e81-b169-e2ab16f41fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>85a8beb4-5173-45b8-9fe1-92e41a7500d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cde7d654b46e33d67318982054d660d9</value>
      <webElementGuid>25c15305-c63d-4486-999e-ab5694b7f7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-field__input ') and (@data-no-activator = '')]</value>
      <webElementGuid>12d46014-b526-4262-bf3b-5052c8a55320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-field__input ') and (@data-no-activator = '')]</value>
      <webElementGuid>b1cc1502-42c1-4ef6-84e9-9a6e53604b14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
