<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>179d1952-9d2f-4973-8ed9-e26d707613cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-login-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-login-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;············&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d063c6d-3937-4b12-af73-84db692e06d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>············</value>
      <webElementGuid>913f92f4-82b3-40a7-b199-7c51c22c3831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7003ac8a-3e6a-4f77-a5f0-d6bdd3bc078a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1a6dbf16-7707-42b8-a0e3-0fa93658731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-login-password-input</value>
      <webElementGuid>155c3a35-f298-402c-b1e9-2650475f3953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-login-password-input-messages</value>
      <webElementGuid>66e13ee4-3a50-4b34-a9d8-66126bec729b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>49f83f92-001b-4333-acf3-b91cccdc1823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32cadad1fbc6d1831165e0c758e153a1</value>
      <webElementGuid>a1a619e6-7348-418b-8e52-65914358c5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-password-input']</value>
      <webElementGuid>305a9f25-2d70-4230-97ec-38c8da57a8d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-password-input']</value>
      <webElementGuid>48f6622b-7f9c-46b5-9907-89fdab8601fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '············' and @type = 'password' and @id = 'admin-login-password-input']</value>
      <webElementGuid>5bb7e53b-ca6b-4be5-9655-9548cf9d7067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
