<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_admin-cards-form-submit-button</name>
   <tag></tag>
   <elementGuidId>aed58098-0970-4f6b-b254-10c4a1968329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-cards-form-submit-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-cards-form-submit-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Simpan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5372b708-735d-4cb1-bcb0-ff6bbf7f55e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1f1ae278-fe91-4b3d-b6ba-51e9ccb07284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--elevated v-theme--dark bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated</value>
      <webElementGuid>eb1340a6-c2ba-4265-82ae-a76767660829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-cards-form-submit-button</value>
      <webElementGuid>ec88b119-92d0-41a1-a6c2-3432af9b5bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Simpan </value>
      <webElementGuid>051bf939-4a5b-4e8b-b3d6-815af85cbe5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b436def7c3ef7405d1124d9dcba4cb6</value>
      <webElementGuid>e82a3c58-3c8f-430b-9579-4e0d5f2c6bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-form-submit-button']</value>
      <webElementGuid>87b10672-4c14-41f8-bb07-faeec570f17e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-form-submit-button']</value>
      <webElementGuid>415ea980-9e3a-4839-a9db-ba03fba45071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'admin-cards-form-submit-button' and (text() = ' Simpan ' or . = ' Simpan ')]</value>
      <webElementGuid>b6fb8d49-e951-44a1-88c8-c9a1eb99755a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
