<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_admingoldentcg.com</name>
   <tag></tag>
   <elementGuidId>653eed66-d738-493f-b279-070f658d0edd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-login-username-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-login-username-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;admin@goldentcg.com&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8628b89b-19b9-49d4-ae36-24c486f77bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>admin@goldentcg.com</value>
      <webElementGuid>1f595380-02ab-4f2d-a959-6bfb6cd38baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a81c07f5-7cdf-4f13-b035-910f52a05033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>896ae99b-4545-4a91-aa7d-66016970d5ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-login-username-input</value>
      <webElementGuid>ea67a858-3be1-4df7-8d60-7d533240493b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-login-username-input-messages</value>
      <webElementGuid>c9208327-1a88-4429-962e-c48b0db72f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>0e4bd07d-9aa6-43ec-8e36-0b8d080b8ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a783ccfe898b03a384d86f0759becbba</value>
      <webElementGuid>39bc8aee-bb3c-42c5-bf6f-11974ae01cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-username-input']</value>
      <webElementGuid>14ae4e8c-fb7a-40c5-9147-57811cdf6b13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-username-input']</value>
      <webElementGuid>8f0528b2-2c08-4ee8-b49c-c39a42835382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'admin@goldentcg.com' and @type = 'email' and @id = 'admin-login-username-input']</value>
      <webElementGuid>378891a9-a008-4de8-8921-bfbd6d409729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
