<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_admin-rarities-toolbar-create-button</name>
   <tag></tag>
   <elementGuidId>782185ac-408d-4ad1-8d89-fb51a004f994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-rarities-toolbar-create-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-rarities-toolbar-create-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tambah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa50d835-8b3f-444b-a948-3a1fd0baa299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--elevated v-theme--dark bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated</value>
      <webElementGuid>4bdc8218-4b4f-4fa2-a844-99156afcfc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/rarities/create</value>
      <webElementGuid>4548046a-716f-44a6-b6c5-827e712cacd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-rarities-toolbar-create-button</value>
      <webElementGuid>a93c7bdf-ff44-4678-b971-9e724fe47719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah </value>
      <webElementGuid>460edb3b-d5a4-4b56-b9cd-edf3bd2668bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d99870d3639b16ce92cb5fe17a0fe42a</value>
      <webElementGuid>868c5a71-fa4c-48db-ab26-84540b5a8733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-rarities-toolbar-create-button']</value>
      <webElementGuid>fc003ea1-15a5-4735-8a61-67ed7b9daff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-rarities-toolbar-create-button']</value>
      <webElementGuid>3e87fe08-339e-4948-adcc-5d19efbb4a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/rarities/create' and @id = 'admin-rarities-toolbar-create-button' and (text() = ' Tambah ' or . = ' Tambah ')]</value>
      <webElementGuid>6811bef5-1f51-46ed-b883-7fa6f051be71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
