<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_v-field_input</name>
   <tag></tag>
   <elementGuidId>b9f7af07-04fd-4e18-bdf7-9d38bfd89f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.v-field__input[data-no-activator=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-field__input ') and (@data-no-activator = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.app-select > .v-input > .v-input__control > .v-field > .v-field__field > .v-field__input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ab2ba74-b2b2-4e39-8fd5-4ac1b6c1faaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>06cf42d5-c89e-475f-b853-38901f02ae88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cde7d654b46e33d67318982054d660d9</value>
      <webElementGuid>ce9f7fcc-a9c4-44a9-8b6d-2b32e8593a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-field__input ') and (@data-no-activator = '')]</value>
      <webElementGuid>a1c64bee-a941-4a5f-a275-b819e19b772d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' v-field__input ') and (@data-no-activator = '')]</value>
      <webElementGuid>b1fdb75c-2227-40a6-bb98-e5814a88de1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
