<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_</name>
   <tag></tag>
   <elementGuidId>b21c5603-f8f4-40a0-b45f-418abf947fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-login-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-login-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;············&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>353df0c5-075a-4dbf-8075-4012e4c6be5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>············</value>
      <webElementGuid>7ef1682f-bd6d-46a0-9ee0-2f3492266c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>84509938-c441-4c4b-aa01-52a9b0b44866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>992ca577-ede8-4fd8-8572-b2f739d10eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-login-password-input</value>
      <webElementGuid>7cb7391d-04d3-4a1d-9e82-b652b89b9ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-login-password-input-messages</value>
      <webElementGuid>b65e372b-93a1-4871-8cb9-3a0647f1c49c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>fde437b7-e2ca-43ee-8c16-83e926578bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32cadad1fbc6d1831165e0c758e153a1</value>
      <webElementGuid>e0f6d221-5fae-4203-9cf9-d82184a0a4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-password-input']</value>
      <webElementGuid>439cf04a-a600-4420-9b39-122ca8b71738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-login-password-input']</value>
      <webElementGuid>00e8e6f5-49fc-4faf-b4a5-3f4ab0876f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '············' and @type = 'password' and @id = 'admin-login-password-input']</value>
      <webElementGuid>8a75deae-3403-4e8a-888c-422546fcd93f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
