<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_admin-games-toolbar-create-button</name>
   <tag></tag>
   <elementGuidId>dc27da5c-b9d2-45ee-a27b-ec81900d9568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-games-toolbar-create-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-games-toolbar-create-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tambah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e56c7f65-894a-48fa-a988-d945ee8d0c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--elevated v-theme--dark bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated</value>
      <webElementGuid>a04afffe-9a7a-4dfd-aa1c-052a7c5d3b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/games/create</value>
      <webElementGuid>b506345f-7a5f-41f9-9bb3-85ed9f906801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-games-toolbar-create-button</value>
      <webElementGuid>03956060-6e30-4448-aba5-a2c07a1b0743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah </value>
      <webElementGuid>94b7216b-741f-48d2-996e-51db4364bff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cc4c38377d5fe9bbe309bdff91a10b13</value>
      <webElementGuid>fa15e1b9-b51a-48de-9048-64bc2e29de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-games-toolbar-create-button']</value>
      <webElementGuid>979bf65a-7022-4fb3-a5ef-32d666035e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-games-toolbar-create-button']</value>
      <webElementGuid>4038a39e-52f9-4c7e-aa32-8d9e2117a74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/games/create' and @id = 'admin-games-toolbar-create-button' and (text() = ' Tambah ' or . = ' Tambah ')]</value>
      <webElementGuid>8a6462ee-6b44-4807-a773-c04a59439ab0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
