<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Deskripsi kartu</name>
   <tag></tag>
   <elementGuidId>3de6f5e9-2023-4780-91d8-991f1270768c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-cards-form-description-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-cards-form-description-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Deskripsi kartu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ac6e1819-1246-4b06-b414-649d1fed6043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>f800ecfb-13b6-4d03-9500-7954fef7f48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Deskripsi kartu</value>
      <webElementGuid>94b98123-2e1d-45da-8c10-dca15c3e8957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>60d56f19-a17c-4754-8365-941c9e2069fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-cards-form-description-textarea</value>
      <webElementGuid>c88129e0-6d45-4132-83e7-dbd169f52cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-cards-form-description-textarea-messages</value>
      <webElementGuid>18be137d-8dc4-46f8-9044-cb9377a25c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f71dba3ecd6d3b919db5334d4acf3200</value>
      <webElementGuid>758f46f0-b30a-45e0-90de-273536fdc75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-form-description-textarea']</value>
      <webElementGuid>edb9bea8-b640-44e9-8193-8ea1346da3ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-form-description-textarea']</value>
      <webElementGuid>c8b9ecc1-8965-491e-8556-e47372f304ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Deskripsi kartu' and @id = 'admin-cards-form-description-textarea']</value>
      <webElementGuid>7d3f8f41-22c4-49fd-8eb2-371a6046a559</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
