<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contoh_ 025_102</name>
   <tag></tag>
   <elementGuidId>80ccdd3d-845b-4421-9800-dda1b6c8db19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-cards-form-card-number-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-cards-form-card-number-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Contoh: 025/102&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49aac511-5a28-41e8-ab64-9fd75967fa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 025/102</value>
      <webElementGuid>0ac9ba30-7f6a-4969-826a-c0f238375240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6536b59d-ddb1-47ae-831a-03882e959a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da3e7020-199d-4a3b-8e8b-596af7f2a408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-cards-form-card-number-input</value>
      <webElementGuid>c76c7bab-8eef-4124-8912-0b9db8167421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>admin-cards-form-card-number-input-messages</value>
      <webElementGuid>cb9d4c11-ea60-40c0-b628-f8660db734ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d05d9c34-413c-4733-a4d6-aeec00d925ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>aadf81d2-37eb-4978-b2fc-bc5a0cc12d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e22489cef645df93ed865beb27124ddc</value>
      <webElementGuid>9114dbb8-d2ee-4c45-8ade-f1c3561c1614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-form-card-number-input']</value>
      <webElementGuid>baede066-c6c5-4aa8-baba-e22bdf425901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-form-card-number-input']</value>
      <webElementGuid>ec49ccb6-948f-4da3-af9e-88598a37af6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Contoh: 025/102' and @type = 'text' and @id = 'admin-cards-form-card-number-input']</value>
      <webElementGuid>12f8a60f-c0fe-4035-acde-6cc4d74845d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
