<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_admin-cards-toolbar-create-button</name>
   <tag></tag>
   <elementGuidId>41f90847-f2c9-4d29-b9d1-3e8ca83b01fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-cards-toolbar-create-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'admin-cards-toolbar-create-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Tambah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>14cd3629-2fe8-40b9-b227-d82c4e6e20e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--elevated v-theme--dark bg-primary v-btn--density-default v-btn--size-default v-btn--variant-elevated</value>
      <webElementGuid>6accd14f-fd34-4d31-9844-813f979191bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cards/create</value>
      <webElementGuid>a25fc588-2164-41e5-a1f7-309e1f1f1582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>admin-cards-toolbar-create-button</value>
      <webElementGuid>e4d3a699-7734-4a6b-939f-85f19d53b0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Tambah </value>
      <webElementGuid>5f67d13c-fb2a-4b1c-82bf-e67c011a3115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2a98ed58463b75124e7d2a982d6f0238</value>
      <webElementGuid>96c3b85c-8b02-4876-84a3-c4f0f9a83b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-toolbar-create-button']</value>
      <webElementGuid>89ad9ad4-b1e4-4e40-84a1-79032c757ea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'admin-cards-toolbar-create-button']</value>
      <webElementGuid>0cf307bb-d12d-4b68-8833-d3aa766b2212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cards/create' and @id = 'admin-cards-toolbar-create-button' and (text() = ' Tambah ' or . = ' Tambah ')]</value>
      <webElementGuid>5463cf2f-ec45-4093-8d54-cda9d72cd367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
